<?php

/**
 *
 * @file
 * Primary module hooks for managepackvhsost module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function managepackvhsost_theme() {
  $hooks['managepackvhsost_blocks'] = [
    'preprocess functions' => [
      'template_preprocess_managepackvhsost_blocks'
    ],
    'render element' => 'element',
    'file' => 'managepackvhsost.theme.inc'
  ];
  return $hooks;
}
